name: Roblox Tracker
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      
      - name: Run Tracker
        run: |
          pip install requests
          python tracker.py
          
      - name: Save Results
        run: |
          git config --global user.name "Tracker-Bot"
          git config --global user.email "bot@github.com"
          git add logs.csv status.json
          git commit -m "Auto-update" || exit 0
          git push
