name: Ro-Tracker-V-2.0
on:
  schedule:
    - cron: '*/5 * * * *' # Backup trigger every 5 mins
  push:
    branches:
      - main # This triggers the loop whenever a file is saved
  workflow_dispatch: # Allows you to run it manually

jobs:
  track:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install Dependencies
        run: pip install requests

      - name: Run Tracker Script
        run: python tracker.py

      - name: Commit and Save Data
        run: |
          git config --global user.name "Tracker-Bot"
          git config --global user.email "bot@github.com"
          git add logs.csv status.json
          git commit -m "Auto-loop update" || exit 0
          git push origin main
